# The makefile for MP3.
#
# make          -- to build program lab3
# make design   -- to verify no illegal variables
# make listtest -- to compile testing program
# make clean    -- to delete object files, executable, and core
# make list.o   -- to compile only list.o
#
# You should not need to change this file.  
#
# Format for each entry
#    target : dependency list of targets or files
#    <tab> command 1
#    <tab> command 2
#    ...
#    <tab> last command
#    <blank line>   -- the list of commands must end with a blank line

lab3 : list.o soc_support.o lab3.o
	gcc -Wall -g list.o soc_support.o lab3.o -o lab3

list.o : list.c datatypes.h list.h
	gcc -Wall -g -c list.c

soc_support.o : soc_support.c datatypes.h list.h soc_support.h
	gcc -Wall -g -c soc_support.c

lab3.o : lab3.c datatypes.h list.h soc_support.h
	gcc -Wall -g -c lab3.c

listtest : listtest.o list.o soc_support.o
	gcc -Wall -g list.o soc_support.o listtest.o -o listtest

listtest.o : listtest.c datatypes.h list.h soc_support.h
	gcc -Wall -g -c listtest.c

#  @ prefix suppresses output of shell command
#  - prefix ignore errors
#  @command || true to avoid Make's error
#  : is shorthand for true
design :
	@grep -e "-> *ll_head" lab3.c soc_support.c ||:
	@grep -e "-> *ll_tail" lab3.c soc_support.c ||:
	@grep -e "-> *ll_entries" lab3.c soc_support.c ||:
	@grep -e "-> *ll_sorted_state" lab3.c soc_support.c ||:
	@grep -e "-> *ll_next" lab3.c soc_support.c ||:
	@grep -e "-> *ll_prev" lab3.c soc_support.c ||:
	@grep -e "-> *data_ptr" lab3.c soc_support.c ||:
	@grep "list_node_t" lab3.c soc_support.c ||:
	@grep "socket_id" list.c ||:
	@grep "dest_ip_addr" list.c ||:
	@grep "socket_t" list.c ||:
	@grep "soc_" list.c ||:

clean :
	rm -f *.o lab3 listtest core a.out

